#!/bin/sh
echo "pkg update && pkg upgrade -y"
echo "termux-setup-storage"
echo "pkg install termux-api"
echo "pkg install git python python2 curl root-repo unstable-repo x11-repo vim termux-tools wget moreutils perl coreutils nodejs texinfo tsu coreutils diffutils libtool make perl clang -y"
echo "apt-get install ncurses-utils"
echo "python3 -m pip install --upgrade pip"
echo "python2 -m pip install --upgrade pip"
echo "python3 -m pip install requests wheel future"
echo "pip install requests wheel future"
echo "pkg install tsu"
echo "git clone https://gitlab.com/st42/termux-sudo"
echo "pkg update && pkg upgrade -y"
